# Generated by Django 5.1.5 on 2025-05-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_manager', '0004_alter_budget_monthly_budget_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='cost',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='name',
            new_name='service_name',
        ),
        migrations.AddField(
            model_name='budget',
            name='alert_threshold',
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name='budget',
            name='cloud_provider',
            field=models.CharField(choices=[('aws', 'Amazon Web Services'), ('gcp', 'Google Cloud Platform'), ('azure', 'Microsoft Azure'), ('all', 'All Providers')], default='all', max_length=10),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.DeleteModel(
            name='BudgetSetting',
        ),
    ]
