# Generated by Django 5.1.5 on 2025-05-10 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_manager', '0005_rename_cost_subscription_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='alert_threshold',
            field=models.PositiveIntegerField(default=80, help_text='Threshold percentage at which to alert the user.'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='cloud_provider',
            field=models.CharField(choices=[('aws', 'Amazon Web Services'), ('gcp', 'Google Cloud Platform'), ('azure', 'Microsoft Azure'), ('all', 'All Providers')], default='all', help_text='Choose which cloud provider this budget applies to.', max_length=10),
        ),
        migrations.AlterField(
            model_name='budget',
            name='monthly_budget',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly budget limit in USD.', max_digits=10),
        ),
        migrations.CreateModel(
            name='CloudAccountUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.FloatField(default=0.0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('cloud_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription_manager.cloudaccount')),
            ],
        ),
    ]
