# Generated by Django 5.1.5 on 2025-05-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_manager', '0007_remove_subscription_user_cloudservicesubscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudservicesubscription',
            name='alert_sent',
            field=models.BooleanField(default=False),
        ),
    ]
