# Generated by Django 5.1.5 on 2025-06-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_manager', '0008_cloudservicesubscription_alert_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudservicesubscription',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='cloudservicesubscription',
            name='usage_amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='cloudservicesubscription',
            name='usage_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cloudservicesubscription',
            name='usage_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cloudservicesubscription',
            name='usage_unit',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='cloudservicesubscription',
            name='renewal_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
