# Generated by Django 5.1.5 on 2025-06-03 17:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_manager', '0009_cloudservicesubscription_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GCPSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('records_synced', models.IntegerField()),
                ('used_dummy', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
