# Generated by Django 5.1.5 on 2025-06-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_manager', '0010_gcpsynclog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gcpsynclog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='gcpsynclog',
            name='records_synced',
        ),
        migrations.RemoveField(
            model_name='gcpsynclog',
            name='used_dummy',
        ),
        migrations.AddField(
            model_name='gcpsynclog',
            name='status',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='gcpsynclog',
            name='synced_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gcpsynclog',
            name='message',
            field=models.TextField(blank=True, default='Zero'),
            preserve_default=False,
        ),
    ]
